#!/bin/bash

ABSURL="https://xfnw.ttm.sh/xfwc"

cat <<EOF > feed.rss
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">

<channel>
<title>xfwc</title>
<link>$ABSURL/</link>
<description>xfwc</description>

EOF

BOOPTMP=$(mktemp)

TOTAL=$(ls src | wc -w)

rm index.html

ln -s $TOTAL.html index.html

NUM=$(( TOTAL ))
for fn in $(ls -t src); do
NEWF=$NUM.html
TITLE=$(echo ${fn%????} | sed 's/_/ /g' | sed -e 's/[]$.*[\^]/\\&/g')
echo "rendering $NEWF..."

cat <<EOF >> feed.rss
<item>
<title>$TITLE</title>
<link>$ABSURL/$NEWF</link>
<description>image #$NUM</description>
</item>
EOF

echo "<img class='comic' alt='$TITLE' title='$TITLE' src='src/$fn'/>" > $BOOPTMP
cp template/page.html $NEWF

sed "/COMIC -->/r $BOOPTMP" template/page.html > $NEWF

sed -i "s/XFSSTITLE/$TITLE/g" $NEWF

sed -i "s/RANDOM/"$(( ( RANDOM % TOTAL ) + 1 ))"/" $NEWF


sed -i "s/LAST/$TOTAL/" $NEWF


[ "$NUM" = "1" ] || sed -i "s/PRE/"$(( NUM - 1 ))"/" $NEWF

[ "$NUM" = "$TOTAL" ] || sed -i "s/NEXT/"$(( NUM + 1 ))"/" $NEWF

sed -i 's/PRE/#/; s/NEXT/#/' $NEWF

NUM=$(( NUM - 1 ))

done

cat <<EOF >> feed.rss
</channel>
</rss>
EOF


